import LegalLayout from './LegalLayout'

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service">
      <p>
        These Terms of Service ("Terms") govern your access to and use of PostPilot, a product
        operated by TabCrypt ("we", "us", "our"). By creating an account or using the Service, you
        agree to be bound by these Terms. If you do not agree, do not use the Service.
      </p>

      <Section title="1. Eligibility">
        <p>
          You must be at least 16 years of age to use the Service. By using PostPilot, you represent
          that you meet this requirement and that you have the authority to enter into these Terms.
        </p>
      </Section>

      <Section title="2. Account Registration">
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and
          for all activity that occurs under your account. You agree to notify us immediately of any
          unauthorized access. We reserve the right to suspend or terminate accounts that violate
          these Terms.
        </p>
      </Section>

      <Section title="3. Service Description">
        <p>
          PostPilot is an AI-powered content generation and social media management tool. The
          Service allows you to:
        </p>
        <ul className="list-disc pl-6 space-y-1 mt-2">
          <li>Generate social media posts using AI providers you configure.</li>
          <li>Publish posts to connected social media accounts.</li>
          <li>Manage templates, post history, and usage quotas.</li>
        </ul>
        <p className="mt-2">
          The Service operates on a "bring-your-own-key" model. You are responsible for obtaining
          and maintaining valid API keys from your chosen AI providers and complying with their
          respective terms of service.
        </p>
      </Section>

      <Section title="4. Plans &amp; Billing">
        <p>
          PostPilot offers free and paid subscription plans. Plan features, limits, and pricing are
          described on our pricing page and may change with reasonable notice. Paid subscriptions are
          billed monthly or annually in advance. Refunds are handled on a case-by-case basis; please
          contact support within 7 days of a charge if you believe it was made in error.
        </p>
      </Section>

      <Section title="5. Acceptable Use">
        <p>
          You agree to use the Service only for lawful purposes and in compliance with our{' '}
          <a href="/acceptable-use" className="text-amber hover:underline">Acceptable Use Policy</a>.
          You must not use the Service to generate or distribute content that is illegal, abusive,
          harassing, defamatory, or that infringes third-party intellectual property rights.
        </p>
      </Section>

      <Section title="6. Intellectual Property">
        <SubSection title="6.1 Your Content">
          <p>
            You retain ownership of the content you create using the Service ("User Content"). By
            using the Service, you grant us a limited, non-exclusive license to process, store, and
            transmit your User Content solely to provide the Service to you.
          </p>
        </SubSection>
        <SubSection title="6.2 Our IP">
          <p>
            The Service, its design, source code, branding, and documentation are the intellectual
            property of TabCrypt and are protected by applicable copyright, trademark, and other
            laws. Nothing in these Terms grants you rights to our trademarks, logos, or branding.
          </p>
        </SubSection>
        <SubSection title="6.3 AI-Generated Content">
          <p>
            Content generated by AI through the Service is produced by third-party AI models. We
            make no claim of ownership over AI-generated output. You are solely responsible for
            reviewing, editing, and verifying AI-generated content before publishing it.
          </p>
        </SubSection>
      </Section>

      <Section title="7. Third-Party Services">
        <p>
          The Service integrates with third-party platforms (e.g., X/Twitter, LinkedIn, Reddit) and
          AI providers (e.g., Anthropic, OpenAI, Google, Groq). Your use of these integrations is
          subject to each provider's terms. We are not responsible for third-party service
          availability, performance, or policy changes.
        </p>
      </Section>

      <Section title="8. Disclaimers">
        <p>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
          WHETHER EXPRESS, IMPLIED, OR STATUTORY. WE DO NOT WARRANT THAT THE SERVICE WILL BE
          UNINTERRUPTED, ERROR-FREE, OR SECURE. WE DISCLAIM ALL WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </p>
        <p className="mt-2">
          AI-generated content may be inaccurate, incomplete, or unsuitable for your intended
          purpose. You are solely responsible for the content you publish.
        </p>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL TABCRYPT, ITS OFFICERS,
          DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA,
          OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE. OUR TOTAL AGGREGATE
          LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING
          THE CLAIM, OR $100, WHICHEVER IS GREATER.
        </p>
      </Section>

      <Section title="10. Indemnification">
        <p>
          You agree to indemnify, defend, and hold harmless TabCrypt and its affiliates from any
          claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from
          your use of the Service, your User Content, or your violation of these Terms.
        </p>
      </Section>

      <Section title="11. Termination">
        <p>
          You may close your account at any time. We may suspend or terminate your access if you
          violate these Terms or for any reason with reasonable notice. Upon termination, your
          right to use the Service ceases immediately. Sections 6, 8, 9, 10, and 12 survive
          termination.
        </p>
      </Section>

      <Section title="12. Governing Law &amp; Disputes">
        <p>
          These Terms are governed by the laws of India. Any disputes arising from these Terms or
          your use of the Service shall be resolved through binding arbitration under the
          Arbitration and Conciliation Act, 1996, conducted in English. You waive any right to
          participate in class-action lawsuits or class-wide arbitration.
        </p>
      </Section>

      <Section title="13. Modifications">
        <p>
          We reserve the right to modify these Terms at any time. Material changes will be
          communicated via the Service or email (if provided). Continued use after changes
          constitutes acceptance.
        </p>
      </Section>

      <Section title="14. Severability">
        <p>
          If any provision of these Terms is found to be unenforceable, the remaining provisions
          will continue in full force and effect.
        </p>
      </Section>

      <Section title="15. Contact">
        <p>
          For questions about these Terms, contact us at{' '}
          <a href="mailto:tabcrypt.in@gmail.com" className="text-amber hover:underline">
            tabcrypt.in@gmail.com
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  )
}

function Section({ title, children }) {
  return (
    <section>
      <h2 className="font-heading font-semibold text-lg text-heading mb-3" style={{ fontFamily: "'Outfit', sans-serif" }}>
        {title}
      </h2>
      {children}
    </section>
  )
}

function SubSection({ title, children }) {
  return (
    <div className="mt-3">
      <h3 className="font-semibold text-heading text-[15px] mb-1">{title}</h3>
      {children}
    </div>
  )
}
